// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dyxj/chess/internal/game (interfaces: Board)
//
// Generated by this command:
//
//	mockgen -destination=mock_interface_test.go -package=game . Board
//

// Package game is a generated GoMock package.
package game

import (
	reflect "reflect"

	engine "github.com/dyxj/chess/internal/engine"
	gomock "go.uber.org/mock/gomock"
)

// MockBoard is a mock of Board interface.
type MockBoard struct {
	ctrl     *gomock.Controller
	recorder *MockBoardMockRecorder
	isgomock struct{}
}

// MockBoardMockRecorder is the mock recorder for MockBoard.
type MockBoardMockRecorder struct {
	mock *MockBoard
}

// NewMockBoard creates a new mock instance.
func NewMockBoard(ctrl *gomock.Controller) *MockBoard {
	mock := &MockBoard{ctrl: ctrl}
	mock.recorder = &MockBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoard) EXPECT() *MockBoardMockRecorder {
	return m.recorder
}

// ActiveColor mocks base method.
func (m *MockBoard) ActiveColor() engine.Color {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveColor")
	ret0, _ := ret[0].(engine.Color)
	return ret0
}

// ActiveColor indicates an expected call of ActiveColor.
func (mr *MockBoardMockRecorder) ActiveColor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveColor", reflect.TypeOf((*MockBoard)(nil).ActiveColor))
}

// ApplyMove mocks base method.
func (m_2 *MockBoard) ApplyMove(m engine.Move) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ApplyMove", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyMove indicates an expected call of ApplyMove.
func (mr *MockBoardMockRecorder) ApplyMove(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMove", reflect.TypeOf((*MockBoard)(nil).ApplyMove), m)
}

// GeneratePieceLegalMoves mocks base method.
func (m *MockBoard) GeneratePieceLegalMoves(p engine.Piece) ([]engine.Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePieceLegalMoves", p)
	ret0, _ := ret[0].([]engine.Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePieceLegalMoves indicates an expected call of GeneratePieceLegalMoves.
func (mr *MockBoardMockRecorder) GeneratePieceLegalMoves(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePieceLegalMoves", reflect.TypeOf((*MockBoard)(nil).GeneratePieceLegalMoves), p)
}

// GridRaw mocks base method.
func (m *MockBoard) GridRaw() [64]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GridRaw")
	ret0, _ := ret[0].([64]int)
	return ret0
}

// GridRaw indicates an expected call of GridRaw.
func (mr *MockBoardMockRecorder) GridRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GridRaw", reflect.TypeOf((*MockBoard)(nil).GridRaw))
}

// HasLegalMoves mocks base method.
func (m *MockBoard) HasLegalMoves(c engine.Color) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasLegalMoves", c)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasLegalMoves indicates an expected call of HasLegalMoves.
func (mr *MockBoardMockRecorder) HasLegalMoves(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasLegalMoves", reflect.TypeOf((*MockBoard)(nil).HasLegalMoves), c)
}

// Is100MoveDraw mocks base method.
func (m *MockBoard) Is100MoveDraw() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Is100MoveDraw")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Is100MoveDraw indicates an expected call of Is100MoveDraw.
func (mr *MockBoardMockRecorder) Is100MoveDraw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Is100MoveDraw", reflect.TypeOf((*MockBoard)(nil).Is100MoveDraw))
}

// Is3FoldDraw mocks base method.
func (m *MockBoard) Is3FoldDraw() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Is3FoldDraw")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Is3FoldDraw indicates an expected call of Is3FoldDraw.
func (mr *MockBoardMockRecorder) Is3FoldDraw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Is3FoldDraw", reflect.TypeOf((*MockBoard)(nil).Is3FoldDraw))
}

// IsCheck mocks base method.
func (m *MockBoard) IsCheck(c engine.Color) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCheck", c)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCheck indicates an expected call of IsCheck.
func (mr *MockBoardMockRecorder) IsCheck(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCheck", reflect.TypeOf((*MockBoard)(nil).IsCheck), c)
}

// Piece mocks base method.
func (m *MockBoard) Piece(c engine.Color, s engine.Symbol, position int) (engine.Piece, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Piece", c, s, position)
	ret0, _ := ret[0].(engine.Piece)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Piece indicates an expected call of Piece.
func (mr *MockBoardMockRecorder) Piece(c, s, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Piece", reflect.TypeOf((*MockBoard)(nil).Piece), c, s, position)
}

// Symbol mocks base method.
func (m *MockBoard) Symbol(pos int) engine.Symbol {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symbol", pos)
	ret0, _ := ret[0].(engine.Symbol)
	return ret0
}

// Symbol indicates an expected call of Symbol.
func (mr *MockBoardMockRecorder) Symbol(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symbol", reflect.TypeOf((*MockBoard)(nil).Symbol), pos)
}

// UndoLastMove mocks base method.
func (m *MockBoard) UndoLastMove() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UndoLastMove")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UndoLastMove indicates an expected call of UndoLastMove.
func (mr *MockBoardMockRecorder) UndoLastMove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UndoLastMove", reflect.TypeOf((*MockBoard)(nil).UndoLastMove))
}
